### ISSUE TITLE
Allow multiple configurations 

### ISSUE THREAD

**Issue by cameront** [smugmug/godynamo#6]
I'd love to be able to connect to two different dynamo tables in my app, which may be owned by different authenticated users.

auth_v4.RawReq is a 'static' function that reads the conf.Vals object every time.

I'd love to be able to initialize a struct with a conf object, which rawReq would read before making the request, rather than the global conf.Vals object.

I think it would presumably still be possible to have a background goroutine looking for config updates (like in the README example)?

I can take a stab at this if it sounds reasonable to you.

**Comment by bradclawsie** [comment]
Hi Justin. Sad to say I am only getting around to looking at this now. Sorry, the holidays and kids have had me tied up. I'm proceeding to try to get this in to my own private branch to run a while before pushing public.

So I see in your conf.go branch, you are using unsafe.*. Is there any particular reason for this? I haven't used this package before so I'm not well versed in the advantages of using it in this way, but the docs seem to indicate fairly strongly that this package circumvents the Go compatibility requirements, so I'm inclined to try to accomplish what you have done here using mainstream packages. I presume just wrapping the setter (SetShared) with mutexes should suffice? If there is something more subtle here, let me know. 

And happy new year!

**Comment by bradclawsie** [comment]
https://github.com/bradclawsie/godynamo/tree/multiple-configs

I am working on this at the above branch in my own repo, little by little. At some point I will be ready to discusses some differences with the PR already offered

**Comment by bradclawsie** [comment]
After thinking about this for a while and hacking away on a halfway counterproposal, I think I want to go back to the drawing board with this if it is to be considered at all. I'd like to open a discussion here to address this at a high level before committing to code.

First, it seems obvious that handling multiple configurations in a single GoDynamo program is something people need and want, and the lack of this feature from the start simply reflects my own use-case.

That said, I feel that this PR just bolts on a new parameter in a way that is incongruous with the existing architecture. 

The new parameter sidesteps the Roles interface as defined in the goawsroles package. Given that the Roles interface was designed specifically to allow new mechanisms for propagating authentication information, I would prefer that we try to extend it for new use-cases.

Using the Roles interface to propagate authentication information would also allow methods to be defined on the Roles instance, allowing safe concurrent reading and updating of temporary credentials. While we can embed a Lock into the conf struct, it doesn't afford the same flexibility as using an interface.

By suggesting that an instance of the Roles interface be used in place of a conf struct, I am assuming that the real issue here is about parameterizing credentials, not parameterizing other values like Host, Port, Zone. It seems unlikely that a caller would want to change these for each request in a running program. If anyone reading this really does need to parameterize more than just credentials, let me know...otherwise I would like to work on a variant of this that exploits the Roles interface.

I'll leave this open for a while to solicit comments.

**Comment by bradclawsie** [comment]
So pursuant to the unveiling of an "official" Go SDK last week (https://aws.amazon.com/blogs/aws/coming-soon-aws-sdk-for-go/)...the best way for me to proceed (imho) is to have the credentials param passed be the one used in the prospective SDK. This will allow users of GoDynamo to more sanely interact with other code using the official SDK while protecting their investment in GoDynamo. I will start tonight working on a way to mate the Roles interface in goawsroles to the prospective SDK credential type.

Comments?

**Comment by bradclawsie** [comment]
I've started working on this here:

https://github.com/bradclawsie/goawsroles/tree/roles_master

sorry, I only realized too late that "roles_master" is a terrible name for a branch.

The point here is to introduce a new Role implementation called RolesMaster which handles "master" credentials. I've also added a new getter which will return the Credentials type used in the soon-to-be-official SDK.

Work in this branch isn't anywhere useful for anything but review and comments.

**Comment by bradclawsie** [comment]
Sorry this PR has been silent for so long and seems to be fairly barren, I have a repo here

https://github.com/bradclawsie/godynamo/tree/credentials_param

that is basically ready soon to be made into a new branch to smugmug/godynamo which should address needs expressed here along with the goawsroles branch above.

Executive summary: no existing code will break, all methods that are relevant now also have a "WithConf" variant that will allow a conf to be passed. It will be more clear when I create a new PR here. soon!

**Comment by bradclawsie** [comment]
My changes are ready as a PR

https://github.com/smugmug/godynamo/pull/17

**Comment by bradclawsie** [comment]
The above PR is currently in use at SmugMug. Barring a comment, it will be merged to master early next week.

**Comment by bradclawsie** [comment]
PR has been merged into master, you may now begin using paramterized configs.
